// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrWP9r9jilGFhz97iAy4k7HJ8bgvyvZyU',
    appId: '1:8111356225:web:59751907490a76b7e889c0',
    messagingSenderId: '8111356225',
    projectId: 'rmconnect2-d9fd3',
    authDomain: 'rmconnect2-d9fd3.firebaseapp.com',
    storageBucket: 'rmconnect2-d9fd3.appspot.com',
    measurementId: 'G-WEXXPGMYDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgBA5UHyW-ScYITaTiUJkn4aX84cfQHdo',
    appId: '1:8111356225:android:700f9cfb06eacfa7e889c0',
    messagingSenderId: '8111356225',
    projectId: 'rmconnect2-d9fd3',
    storageBucket: 'rmconnect2-d9fd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaSBtv7EBRxvmYjfvnxSR_wwsEAEdK4UI',
    appId: '1:8111356225:ios:053c6922600dfa9be889c0',
    messagingSenderId: '8111356225',
    projectId: 'rmconnect2-d9fd3',
    storageBucket: 'rmconnect2-d9fd3.appspot.com',
    iosBundleId: 'com.example.rmConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaSBtv7EBRxvmYjfvnxSR_wwsEAEdK4UI',
    appId: '1:8111356225:ios:99cad85199ccc80de889c0',
    messagingSenderId: '8111356225',
    projectId: 'rmconnect2-d9fd3',
    storageBucket: 'rmconnect2-d9fd3.appspot.com',
    iosBundleId: 'com.example.rmConnect.RunnerTests',
  );
}
